## Cleaning dataset

-Importing dataset(2003-2007) and libraries

In [2]:
# !pip install pandas
# !pip install numpy
import math
import numpy as np 
import pandas as pd

In [5]:
#Importing dataset 
Y2003 = pd.read_csv("C:/Users/Admin/Desktop/ST2195_Programming_for_datascience/Coursework/dataset/2003_old.csv", encoding='latin-1', low_memory= False)
Y2004 = pd.read_csv("C:/Users/Admin/Desktop/ST2195_Programming_for_datascience/Coursework/dataset/2004_old.csv", encoding='latin-1', low_memory= False)
Y2005 = pd.read_csv("C:/Users/Admin/Desktop/ST2195_Programming_for_datascience/Coursework/dataset/2005_old.csv", encoding='latin-1', low_memory= False)
Y2006 = pd.read_csv("C:/Users/Admin/Desktop/ST2195_Programming_for_datascience/Coursework/dataset/2006_old.csv", encoding='latin-1', low_memory= False)
Y2007 = pd.read_csv("C:/Users/Admin/Desktop/ST2195_Programming_for_datascience/Coursework/dataset/2007_old.csv", encoding='latin-1', low_memory= False)

In [16]:
Y2003.describe

<bound method NDFrame.describe of          Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0        2003      1          29          3   1651.0        1655   1912.0
1        2003      1          30          4   1654.0        1655   1910.0
2        2003      1          31          5   1724.0        1655   1936.0
3        2003      1           1          3   1033.0        1035   1625.0
4        2003      1           2          4   1053.0        1035   1726.0
...       ...    ...         ...        ...      ...         ...      ...
6488535  2003     12           5          5   1126.0        1110   1326.0
6488536  2003     12           5          5   2100.0        2010   2240.0
6488537  2003     12           5          5   1142.0        1145   1217.0
6488538  2003     12           5          5    623.0         620    911.0
6488539  2003     12           5          5   1024.0        1025   1626.0

         CRSArrTime UniqueCarrier  FlightNum  ... TaxiIn  TaxiOut  Cancelled  \
0              1913            UA       1017  ...      5       17          0
1              1913            UA       1017  ...      2       26          0
2              1913            UA       1017  ...      5       17          0
3              1634            UA       1018  ...      6       11          0
4              1634            UA       1018  ...     13       46          0
...             ...           ...        ...  ...    ...      ...        ...
6488535        1239            DL        794  ...     31       20          0
6488536        2146            DL        798  ...      8       21          0
6488537        1222            DL        799  ...      4       15          0
6488538         908            DL        800  ...      6       14          0
6488539        1627            DL        800  ...      6       21          0

         CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  \
0                     NaN         0           NaN          NaN      NaN
1                     NaN         0           NaN          NaN      NaN
2                     NaN         0           NaN          NaN      NaN
3                     NaN         0           NaN          NaN      NaN
4                     NaN         0           NaN          NaN      NaN
...                   ...       ...           ...          ...      ...
6488535               NaN         0           0.0          0.0     31.0
6488536               NaN         0           3.0          0.0      4.0
6488537               NaN         0           0.0          0.0      0.0
6488538               NaN         0           0.0          0.0      0.0
6488539               NaN         0           0.0          0.0      0.0

         SecurityDelay  LateAircraftDelay
0                  NaN                NaN
1                  NaN                NaN
2                  NaN                NaN
3                  NaN                NaN
4                  NaN                NaN
...                ...                ...
6488535            0.0               16.0
6488536            0.0               47.0
6488537            0.0                0.0
6488538            0.0                0.0
6488539            0.0                0.0

[6488540 rows x 29 columns]>

In [6]:
Y2003.isnull().sum()

Year                       0
Month                      0
DayofMonth                 0
DayOfWeek                  0
DepTime               101469
CRSDepTime                 0
ArrTime               112850
CRSArrTime                 0
UniqueCarrier              0
FlightNum                  0
TailNum                26336
ActualElapsedTime     112851
CRSElapsedTime             1
AirTime               112850
ArrDelay              112851
DepDelay              101469
Origin                     0
Dest                       0
Distance                   0
TaxiIn                     0
TaxiOut                    0
Cancelled                  0
CancellationCode     6435446
Diverted                   0
CarrierDelay         2672742
WeatherDelay         2672742
NASDelay             2672742
SecurityDelay        2672742
LateAircraftDelay    2672742
dtype: int64

In [7]:
Y2003.describe()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,FlightNum,ActualElapsedTime,...,Distance,TaxiIn,TaxiOut,Cancelled,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,6488540.0,6.488540e+06,6.488540e+06,6.488540e+06,6.387071e+06,6.488540e+06,6.375690e+06,6.488540e+06,6.488540e+06,6.375689e+06,...,6.488540e+06,6.488540e+06,6.488540e+06,6.488540e+06,6.488540e+06,3.815798e+06,3.815798e+06,3.815798e+06,3.815798e+06,3.815798e+06
mean,2003.0,6.525727e+00,1.571836e+01,3.930434e+00,1.344690e+03,1.341220e+03,1.504361e+03,1.510046e+03,2.013294e+03,1.223836e+02,...,7.114300e+02,7.054598e+00,1.508602e+01,1.563819e-02,1.754016e-03,2.245475e+00,5.207705e-01,3.108801e+00,2.113922e-02,2.631879e+00
std,0.0,3.450800e+00,8.778332e+00,1.988876e+00,4.655073e+02,4.574301e+02,4.820910e+02,4.693388e+02,1.937488e+03,6.963624e+01,...,5.639965e+02,3.604676e+01,1.061370e+01,1.240711e-01,4.184423e-02,1.537969e+01,7.697381e+00,1.419860e+01,1.100385e+00,1.460277e+01
min,2003.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,-6.900000e+02,...,1.100000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-6.000000e+01,0.000000e+00,0.000000e+00
25%,2003.0,4.000000e+00,8.000000e+00,2.000000e+00,9.400000e+02,9.380000e+02,1.127000e+03,1.131000e+03,5.830000e+02,7.100000e+01,...,3.030000e+02,4.000000e+00,1.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2003.0,7.000000e+00,1.600000e+01,4.000000e+00,1.330000e+03,1.330000e+03,1.527000e+03,1.530000e+03,1.405000e+03,1.030000e+02,...,5.470000e+02,5.000000e+00,1.300000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,2003.0,1.000000e+01,2.300000e+01,6.000000e+00,1.730000e+03,1.725000e+03,1.914000e+03,1.910000e+03,2.723000e+03,1.530000e+02,...,9.460000e+02,7.000000e+00,1.800000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
max,2003.0,1.200000e+01,3.100000e+01,7.000000e+00,2.735000e+03,2.400000e+03,2.920000e+03,2.400000e+03,9.766000e+03,1.777000e+03,...,4.962000e+03,1.495000e+03,1.436000e+03,1.000000e+00,1.000000e+00,1.582000e+03,1.160000e+03,1.385000e+03,2.300000e+02,1.407000e+03

In [8]:
Y2003

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2003,1,29,3,1651.0,1655,1912.0,1913,UA,1017,...,5,17,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,2003,1,30,4,1654.0,1655,1910.0,1913,UA,1017,...,2,26,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2003,1,31,5,1724.0,1655,1936.0,1913,UA,1017,...,5,17,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2003,1,1,3,1033.0,1035,1625.0,1634,UA,1018,...,6,11,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,2003,1,2,4,1053.0,1035,1726.0,1634,UA,1018,...,13,46,0,NaN,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6488535,2003,12,5,5,1126.0,1110,1326.0,1239,DL,794,...,31,20,0,NaN,0,0.0,0.0,31.0,0.0,16.0
6488536,2003,12,5,5,2100.0,2010,2240.0,2146,DL,798,...,8,21,0,NaN,0,3.0,0.0,4.0,0.0,47.0
6488537,2003,12,5,5,1142.0,1145,1217.0,1222,DL,799,...,4,15,0,NaN,0,0.0,0.0,0.0,0.0,0.0
6488538,2003,12,5,5,623.0,620,911.0,908,DL,800,...,6,14,0,NaN,0,0.0,0.0,0.0,0.0,0.0
6488539,2003,12,5,5,1024.0,1025,1626.0,1627,DL,800,...,6,21,0,NaN,0,0.0,0.0,0.0,0.0,0.0

In [10]:
Y2004

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2004,1,12,1,623.0,630,901.0,915,UA,462,...,7,11,0,NaN,0,0,0,0,0,0
1,2004,1,13,2,621.0,630,911.0,915,UA,462,...,16,16,0,NaN,0,0,0,0,0,0
2,2004,1,14,3,633.0,630,920.0,915,UA,462,...,4,15,0,NaN,0,0,0,0,0,0
3,2004,1,15,4,627.0,630,859.0,915,UA,462,...,4,10,0,NaN,0,0,0,0,0,0
4,2004,1,16,5,635.0,630,918.0,915,UA,462,...,3,13,0,NaN,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7129265,2004,12,16,4,1645.0,1639,1715.0,1716,DL,1138,...,4,13,0,NaN,0,0,0,0,0,0
7129266,2004,12,16,4,726.0,720,1238.0,1239,DL,1139,...,10,11,0,NaN,0,0,0,0,0,0
7129267,2004,12,16,4,1336.0,1330,1507.0,1504,DL,1139,...,5,10,0,NaN,0,0,0,0,0,0
7129268,2004,12,16,4,538.0,540,720.0,723,DL,1140,...,7,12,0,NaN,0,0,0,0,0,0
7129269,2004,12,16,4,811.0,813,955.0,1008,DL,1140,...,7,12,0,NaN,0,0,0,0,0,0

In [11]:
Y2005

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2005,1,28,5,1603.0,1605,1741.0,1759,UA,541,...,4,23,0,NaN,0,0,0,0,0,0
1,2005,1,29,6,1559.0,1605,1736.0,1759,UA,541,...,6,15,0,NaN,0,0,0,0,0,0
2,2005,1,30,7,1603.0,1610,1741.0,1805,UA,541,...,9,18,0,NaN,0,0,0,0,0,0
3,2005,1,31,1,1556.0,1605,1726.0,1759,UA,541,...,11,10,0,NaN,0,0,0,0,0,0
4,2005,1,2,7,1934.0,1900,2235.0,2232,UA,542,...,5,10,0,NaN,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7140591,2005,12,22,4,1652.0,1655,1815.0,1837,DL,901,...,7,15,0,NaN,0,0,0,0,0,0
7140592,2005,12,22,4,1825.0,1825,1858.0,1848,DL,902,...,7,32,0,NaN,0,0,0,0,0,0
7140593,2005,12,22,4,1507.0,1511,1641.0,1649,DL,903,...,4,29,0,NaN,0,0,0,0,0,0
7140594,2005,12,22,4,924.0,925,1056.0,1111,DL,904,...,4,19,0,NaN,0,0,0,0,0,0
7140595,2005,12,22,4,1345.0,1344,1621.0,1614,DL,905,...,6,27,0,NaN,0,0,0,0,0,0

In [13]:
Y2006

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2006,1,11,3,743.0,745,1024.0,1018,US,343,...,45,13,0,NaN,0,0,0,0,0,0
1,2006,1,11,3,1053.0,1053,1313.0,1318,US,613,...,27,19,0,NaN,0,0,0,0,0,0
2,2006,1,11,3,1915.0,1915,2110.0,2133,US,617,...,4,11,0,NaN,0,0,0,0,0,0
3,2006,1,11,3,1753.0,1755,1925.0,1933,US,300,...,16,10,0,NaN,0,0,0,0,0,0
4,2006,1,11,3,824.0,832,1015.0,1015,US,765,...,27,12,0,NaN,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7141917,2006,12,29,5,1246.0,1249,1452.0,1459,DL,1675,...,6,12,0,NaN,0,0,0,0,0,0
7141918,2006,12,29,5,1225.0,1155,2033.0,1931,DL,1676,...,12,35,0,NaN,0,30,0,32,0,0
7141919,2006,12,29,5,2118.0,2115,2254.0,2241,DL,1676,...,9,27,0,NaN,0,0,0,0,0,0
7141920,2006,12,29,5,2122.0,2127,2209.0,2223,DL,1677,...,5,21,0,NaN,0,0,0,0,0,0
7141921,2006,12,29,5,2042.0,2045,2213.0,2235,DL,1678,...,5,15,0,NaN,0,0,0,0,0,0

In [14]:
Y2007

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2007,1,1,1,1232.0,1225,1341.0,1340,WN,2891,...,4,11,0,NaN,0,0,0,0,0,0
1,2007,1,1,1,1918.0,1905,2043.0,2035,WN,462,...,5,6,0,NaN,0,0,0,0,0,0
2,2007,1,1,1,2206.0,2130,2334.0,2300,WN,1229,...,6,9,0,NaN,0,3,0,0,0,31
3,2007,1,1,1,1230.0,1200,1356.0,1330,WN,1355,...,3,8,0,NaN,0,23,0,0,0,3
4,2007,1,1,1,831.0,830,957.0,1000,WN,2278,...,3,9,0,NaN,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7453210,2007,12,15,6,1558.0,1605,1749.0,1736,DL,58,...,14,17,0,NaN,0,0,0,0,0,0
7453211,2007,12,15,6,1902.0,1851,2110.0,2105,DL,59,...,6,21,0,NaN,0,0,0,0,0,0
7453212,2007,12,15,6,1024.0,1025,1750.0,1735,DL,61,...,14,19,0,NaN,0,0,0,15,0,0
7453213,2007,12,15,6,1353.0,1315,1658.0,1622,DL,62,...,11,14,0,NaN,0,0,0,0,0,36
7453214,2007,12,15,6,1824.0,1800,2001.0,1928,DL,63,...,10,26,0,NaN,0,24,0,9,0,0

In [17]:
df = pd.concat([Y2003, Y2004, Y2005, Y2006, Y2007], ignore_index=True)

In [18]:
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2003,1,29,3,1651.0,1655,1912.0,1913,UA,1017,...,5,17,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,2003,1,30,4,1654.0,1655,1910.0,1913,UA,1017,...,2,26,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2003,1,31,5,1724.0,1655,1936.0,1913,UA,1017,...,5,17,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2003,1,1,3,1033.0,1035,1625.0,1634,UA,1018,...,6,11,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,2003,1,2,4,1053.0,1035,1726.0,1634,UA,1018,...,13,46,0,NaN,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35353538,2007,12,15,6,1558.0,1605,1749.0,1736,DL,58,...,14,17,0,NaN,0,0.0,0.0,0.0,0.0,0.0
35353539,2007,12,15,6,1902.0,1851,2110.0,2105,DL,59,...,6,21,0,NaN,0,0.0,0.0,0.0,0.0,0.0
35353540,2007,12,15,6,1024.0,1025,1750.0,1735,DL,61,...,14,19,0,NaN,0,0.0,0.0,15.0,0.0,0.0
35353541,2007,12,15,6,1353.0,1315,1658.0,1622,DL,62,...,11,14,0,NaN,0,0.0,0.0,0.0,0.0,36.0
35353542,2007,12,15,6,1824.0,1800,2001.0,1928,DL,63,...,10,26,0,NaN,0,24.0,0.0,9.0,0.0,0.0

In [19]:
df.isnull().sum()

Year                        0
Month                       0
DayofMonth                  0
DayOfWeek                   0
DepTime                645638
CRSDepTime                  0
ArrTime                718196
CRSArrTime                  0
UniqueCarrier               0
FlightNum                   0
TailNum                 26485
ActualElapsedTime      718197
CRSElapsedTime            999
AirTime                718196
ArrDelay               718197
DepDelay               645638
Origin                      0
Dest                        0
Distance                    0
TaxiIn                      0
TaxiOut                     0
Cancelled                   0
CancellationCode     34756271
Diverted                    0
CarrierDelay          2672742
WeatherDelay          2672742
NASDelay              2672742
SecurityDelay         2672742
LateAircraftDelay     2672742
dtype: int64

In [22]:
#saving combined dataset
df.to_csv("C:/Users/Admin/Desktop/ST2195_Programming_for_datascience/Coursework/dataset", index=False)

PermissionError: [Errno 13] Permission denied: 'C:/Users/Admin/Desktop/ST2195_Programming_for_datascience/Coursework/dataset'